language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t alexvapniaruk/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true alexvapniaruk/docker-react npm run test

deploy:
  provider: elasricbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-186472829541"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY